REGRESSION(287403@main): Unable to link libjavascriptcoregtk: undefined reference to `ipint_extern_prepare_call_ref' https://bugs.webkit.org/show_bug.cgi?id=286433
Reviewed by Yusuke Suzuki.

The names of these macros are a little confusing, but I gather that
HIDDEN is supposed to be used for declarations in header files.

* Source/JavaScriptCore/wasm/WasmIPIntSlowPaths.h:

Canonical link: https://commits.webkit.org/289320@main